### ISSUE TITLE
希望新增 dashboard: 全市病例趋势

### ISSUE THREAD

**Issue by sinchang** [kekincai/shanghai_covid19#1]
首先很感谢您开发这个项目，非常有帮助。

现在已经有各区的病例趋势分析，不知道是否方便新增全市的病例趋势，也可通过如下三个选择去展示不同的趋势：
- 全体数据
- 无症状
- 确诊

谢谢

**Comment by kekincai** [comment]
全市的趋势后面可以加上。
> 全体数据
全体数据里因为会有无症状转确诊，判断和统计起来比较麻烦。。。再加上无症状患者占比超过九十，只看无症状的应该不影响判断。

**Comment by sinchang** [comment]
@kekincai 嗯，谢谢
